# Netlify Configuration File
# This file optimizes your portfolio deployment on Netlify

[build]
  # No build process needed - static site
  publish = "."

[build.environment]
  # Node version (if needed for any build tools)
  NODE_VERSION = "18"

[[headers]]
  # Apply headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Special caching for HTML files
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Long cache for assets
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # CORS for 3D models if needed
  for = "*.glb"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  # Handle contact form thank you page
  from = "/contact-success"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  # Handle 404s by redirecting to home
  from = "/*"
  to = "/index.html"
  status = 404

# Form handling (Netlify Forms)
# This enables form submissions without additional setup
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true
